### ISSUE TITLE
Ship compare wood selection appends next wood choice

### ISSUE THREAD

**Issue by Jameson1151** [felixvictor/na-map#3]
Changing woods in ship compare is appending the 2nd choice and not updating stats. Refresh of site is a workaround.

Left ship, Oak auto fills after selecting frame, this is for all 3 compare sections. Changed Oak to Fir(S), appends to the front.
Right ship, Oak auto fills after selecting frame, Changed Oak to RigaFir, appends to the end.
Perhaps removing the auto fill and adding a "Clear Woods" button would help?
![Naval Action map](https://user-images.githubusercontent.com/9636711/187097645-0c2ae4a9-ad33-4249-939f-3e66cc7915ac.png)

**Comment by felixvictor** [comment]
The library for selects is buggy and not properly maintained anymore, c.f. https://github.com/snapappointments/bootstrap-select/issues/2738. I tried to fix it but failed.

Sadly, I cannot commit more time on this, therefore I close this issue. If the library is fixed (but do not count on it), I will update the map.

**Comment by felixvictor** [comment]
As someone posted a workaround I could hotfix it.
